version: 2

build:
  image: latest

python:
  version: 3.8
  setup_py_install: true

dependencies:
  override:
    - pip install -r source/requirements.txt

docs:
  - check
  - build:
      type: Sphinx
      builder: html
      configuration: source/conf.py
